- hosts: localhost
  vars_files:
    - aws.yml

  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: redhate_work
        instance_type: t2.micro
        image: ami-08e0ca9924195beba
        wait: yes
        count: 3
        region: ap-south-1
        instance_tags:
          Name: k8S
        vpc_subnet_id: subnet-84040dec
        group_id: sg-14865f73
        state: present
    - name: execute install script
      script: ec2.py

 
